//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::tac_operation_ids::Entity as TacOperationIds;
pub use super::tac_operation_stages::Entity as TacOperationStages;
pub use super::tac_tasks::Entity as TacTasks;
