//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tac_operation_ids")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub id: Vec<u8>,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tac_operation_stages::Entity")]
    TacOperationStages,
}

impl Related<super::tac_operation_stages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TacOperationStages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
