//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tac_operation_stages")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub operation_id: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub stage: String,
    pub timestamp: DateTime,
    pub successful: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tac_operation_ids::Entity",
        from = "Column::OperationId",
        to = "super::tac_operation_ids::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TacOperationIds,
}

impl Related<super::tac_operation_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TacOperationIds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
